# Generated by Django 5.0.3 on 2024-03-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_tagcategory_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
